[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "echo 'No build step needed'"

[start]
cmd = "python web.py"