services:
  - type: web
    name: aeonforge-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.7
    healthCheckPath: /
    autoDeploy: true
    repo: https://github.com/kstephens0331/aeonforge.git
    branch: main